# Generated by Django 4.2.28 on 2026-02-24 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_account_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency Fund"),
                            ("vacation", "Vacation"),
                            ("car", "Car"),
                            ("home", "Home"),
                            ("education", "Education"),
                            ("retirement", "Retirement"),
                            ("investment", "Investment"),
                            ("debt_payoff", "Debt Payoff"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("target_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="savings_goals",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Savings Goals",
                "db_table": "savings_goals",
                "ordering": ["-priority", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="GoalMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="goals.savingsgoal",
                    ),
                ),
            ],
            options={
                "db_table": "goal_milestones",
                "ordering": ["target_amount"],
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("contribution_date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source of contribution (e.g., salary, bonus)",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="goals.savingsgoal",
                    ),
                ),
            ],
            options={
                "db_table": "goal_contributions",
                "ordering": ["-contribution_date"],
            },
        ),
    ]
