# Generated by Django 4.2.28 on 2026-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
