# Generated by Django 4.2.28 on 2026-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("CHF", "Swiss Franc"),
                    ("SGD", "Singapore Dollar"),
                    ("AED", "UAE Dirham"),
                    ("BDT", "Bangladeshi Taka"),
                    ("BRL", "Brazilian Real"),
                    ("KRW", "South Korean Won"),
                    ("MYR", "Malaysian Ringgit"),
                    ("THB", "Thai Baht"),
                    ("ZAR", "South African Rand"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("NZD", "New Zealand Dollar"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
    ]
