# Generated by Django 4.2.28 on 2026-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("CHF", "Swiss Franc"),
                    ("SGD", "Singapore Dollar"),
                    ("AED", "UAE Dirham"),
                    ("BDT", "Bangladeshi Taka"),
                    ("BRL", "Brazilian Real"),
                    ("KRW", "South Korean Won"),
                    ("MYR", "Malaysian Ringgit"),
                    ("THB", "Thai Baht"),
                    ("ZAR", "South African Rand"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("NZD", "New Zealand Dollar"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Exchange rate used for conversion",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount in original currency before conversion",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("CHF", "Swiss Franc"),
                    ("SGD", "Singapore Dollar"),
                    ("AED", "UAE Dirham"),
                    ("BDT", "Bangladeshi Taka"),
                    ("BRL", "Brazilian Real"),
                    ("KRW", "South Korean Won"),
                    ("MYR", "Malaysian Ringgit"),
                    ("THB", "Thai Baht"),
                    ("ZAR", "South African Rand"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("NZD", "New Zealand Dollar"),
                ],
                help_text="Original currency if different from user preferred currency",
                max_length=3,
                null=True,
            ),
        ),
    ]
